#!/bin/bash

HOST=marcela@pluto.cs.princeton.edu
SRC=/home/marcela/Research/lib-isolation/libpyronia/libraries/libsmv
LIBDIR=/home/pyronia/pyronia-linux/testing/libpyronia/libraries

rsync -rczv $HOST:$SRC $LIBDIR

cd $LIBDIR
cd libsmv
make
make install
