#!/bin/bash

SRCDIR=$HOME/libpyronia/libraries/libsmv/testcases

gcc -g $SRCDIR/memdom_ops_tests.c -o $HOME/memdom_ops_test -lsmv
gcc -g $SRCDIR/memdom_fault_tests.c -o $HOME/memdom_fault_test -lsmv -lpthread
gcc -g $SRCDIR/smv_ops_tests.c -o $HOME/smv_ops_test -lsmv
gcc -g $SRCDIR/smvthread_ops_tests.c -o $HOME/smvthread_ops_test -lsmv -lpthread
gcc -g $SRCDIR/tc_memdom_alloc.c -o $HOME/tc_memdom_alloc_test -lsmv -lpthread
gcc -g $SRCDIR/tc_memdom_create.c -o $HOME/tc_memdom_create_test -lsmv -lpthread
gcc -g $SRCDIR/tc_smv_create.c -o $HOME/tc_smv_create_test -lsmv -lpthread
gcc -g $SRCDIR/tc_smvthread_create.c -o $HOME/tc_smvthread_create_test -lsmv -lpthread
gcc -g $SRCDIR/tc_shared_mm.c -o $HOME/tc_shared_mm_test -lsmv -lpthread
gcc -g $SRCDIR/privs_t1.c -o $HOME/privs_test -lsmv -lpthread
gcc -g $SRCDIR/tc_cond_var.c -o $HOME/tc_cond_var_test -lsmv -lpthread

cd $HOME

echo "*** Running End-to-End Kernel Tests***"

./memdom_ops_test
./memdom_fault_test
./smv_ops_test
./smvthread_ops_test
./tc_memdom_create_test
./tc_memdom_alloc_test
./tc_smv_create_test
./tc_smvthread_create_test
./tc_shared_mm_test
./tc_cond_var_test
./privs_test
